### ISSUE TITLE
Big Sur: emoji's invisible + after "init emoji", no emoji's found

### ISSUE THREAD

**Issue by brainbaking** [jeeftor/EmojiTaco#18] opened 2021-01-14 10:19 UTC
Hi there,

On Big Sur, the emoji's aren't displayed in the result list in Alfred. They copy-paste fine, so that still works.  I've seen I'm not the only one with this problem: see the Alfred forum post of november, 2020, here: https://www.alfredforum.com/topic/9499-emoji-taco-downloads-emoji-from-unicodeorg/ - I'm copying his screenshot:

![](https://content.invisioncic.com/r229491/monthly_2020_11/520273288_ScreenShot2020-11-13at12_33_00AM.jpg.f807c6765a17b3e2e06f5975a4c26b78.jpg)

I did not know about `init emoji` so I thought, let's run that. But after that's done, no results _at all_ are found... Only after re-installing it works again (with invisible emojis)

Thanks for looking into this!

**Comment by jeeftor** [comment] 2021-01-14 11:07
I’ll take a look.

**Comment by jeeftor** [comment] 2021-01-16 13:38
So I'm running Catalina and don't see this behavior. I may have to wait until BigSur to see what has changed. Internally what the plugin is doing is pulling down this page: https://unicode.org/emoji/charts/full-emoji-list.html and pulling the emoji images out of it and turning them into pictures on your system. 

If you are able to open the workflow directory on your system and navigate to the `img` folder - do you see anything?
<img width="453" alt="Screen Shot 2021-01-16 at 6 39 59 AM" src="https://user-images.githubusercontent.com/6491743/104813315-b1514800-57c5-11eb-99d2-4535c1ba1226.png">




<img width="246" alt="Screen Shot 2021-01-16 at 6 40 38 AM" src="https://user-images.githubusercontent.com/6491743/104813349-d6de5180-57c5-11eb-9ea8-1fe692fdce8b.png">

**Comment by jeeftor** [comment] 2021-01-16 13:42
If images are showing up there could be some tweak in BigSur - if they aren't showing up its hard to say what the issue is w/out upgrading my system (which will eventually happen)

**Comment by peterkracik** [comment] 2021-01-22 13:25
+1

**Comment by jeeftor** [comment] 2021-01-22 14:23
Can either of you guys verify the image files exist on disk as I showed how
to check? Again I'm not running Big Sur currently

**Comment by peterkracik** [comment] 2021-01-22 14:31
@jeeftor no, the folder is empty. I tried to download the workflow and to try copy those images, but the folder was empty as well. should it be this way?

**Comment by peterkracik** [comment] 2021-01-22 14:39
@jeeftor I found the problem. I didn't initialize the workflow (as it was written). sorry for that.

for others, make sure to run `init emoji` first

**Comment by jeeftor** [comment] 2021-01-22 14:51
Cool, thanks!

I'll leave this issue open for now until i can get more confirmation from
others its a problem or not a problem.

**Comment by homerjay88xx** [comment] 2021-02-06 13:17
It is not working for me....
I did the init, but the img folder stays empty. No emojis are found

**Comment by jeeftor** [comment] 2021-03-01 18:04
Testing with Big Sur now...

**Comment by jeeftor** [comment] 2021-03-01 18:10
I deleted all the images and it worked for me. If you still have issue please let me know.

You can try the `dbgemoji` menu to open the log and explore some debug stuff...

**Comment by jeeftor** [comment] 2021-03-12 19:35
I could not duplicate this. Sorry. Closing issue

**Closed as completed** 2021-03-12 19:35 UTC

**Comment by 1activegeek** [comment] 2021-10-17 03:34
Having this exact issue on macOS 11.6. No images to start with. After `init emoji` it fails to find any emoji. Checking the log from `dbgemoji` shows this issue:
```
23:21:43 bg_downloader.py:44 INFO     Creating DataFileBuilder
23:21:44 workflow.py:2074 ERROR    Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
Traceback (most recent call last):
  File "/Users/shawnmix/Documents/Backup and Recovery/appdata/Alfred.alfredpreferences/workflows/user.workflow.1BB19704-D81A-4C3F-A60E-7450A84FDC73/src/workflow/workflow.py", line 2067, in run
    func(self)
  File "/Users/shawnmix/Documents/Backup and Recovery/appdata/Alfred.alfredpreferences/workflows/user.workflow.1BB19704-D81A-4C3F-A60E-7450A84FDC73/src/bg_downloader.py", line 38, in main
    parseFiles()
  File "/Users/shawnmix/Documents/Backup and Recovery/appdata/Alfred.alfredpreferences/workflows/user.workflow.1BB19704-D81A-4C3F-A60E-7450A84FDC73/src/bg_downloader.py", line 50, in parseFiles
    parse_html_file(csv, 'full-emoji-list.html', msg)
  File "/Users/shawnmix/Documents/Backup and Recovery/appdata/Alfred.alfredpreferences/workflows/user.workflow.1BB19704-D81A-4C3F-A60E-7450A84FDC73/src/bg_downloader.py", line 141, in parse_html_file
    soup = BeautifulSoup(html, "lxml")
  File "/Users/shawnmix/Documents/Backup and Recovery/appdata/Alfred.alfredpreferences/workflows/user.workflow.1BB19704-D81A-4C3F-A60E-7450A84FDC73/src/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

Attempted to fix this, by running `pip3 instal lxml` since I'm assuming I just didn't have that parser available. Doing so got me past that error, but now as soon as it finishes downloading the emoji data, it clears the log and prints out just this:

`23:30:29 background.py:285 ERROR    [bg] command failed with status 1`

I also checked the directory mentioned for the workflow, and see NO images in the img folder.

**Comment by jeeftor** [comment] 2021-10-17 04:16
I’ve stumbled on this bug as well. I’ll be traveling for work in a couple weeks. So if I can’t fix it prior I’ll do it on that trip.

**Comment by jeeftor** [comment] 2021-10-17 12:20
I think I have a fix but the kids just woke up. I'll push something either today or this week.

**Comment by 1activegeek** [comment] 2021-10-17 21:01
Sounds great. I'll keep an eye out for the update and will pull it down to try out.
